/**
 * Phase 6: Cloud → MMKV bootstrap.
 *
 * Companion to `cloud-sync.ts`. When a user signs in on a fresh
 * device (no MMKV state yet), the legacy stores would render empty
 * even though the cloud has all their data. This bootstrap pulls
 * cloud data into MMKV at sign-in time so the legacy stores are
 * populated before any screen renders them.
 *
 * Run order at sign-in:
 *   1. Auth resolves
 *   2. MigrationGate runs migrate-to-supabase (MMKV → cloud) for
 *      first-time cloud users; if MMKV is already empty, this is a no-op.
 *   3. cloud-bootstrap runs (cloud → MMKV) to populate any stores
 *      where MMKV is empty but cloud has rows. Idempotent — skips
 *      stores that already have local data.
 *   4. cloud-sync starts subscribing for ongoing writes.
 *
 * The bootstrap is one-shot: once it has populated a store, it
 * doesn't run again for that store on the same device. We track this
 * via a per-user, per-domain MMKV flag (`bootstrap_<domain>_done:<userId>`).
 */

import { storage, setJSON, getJSON } from "../db/storage";
import { logError } from "./error-log";
import * as budgetsService from "../services/budgets";
import * as weightService from "../services/weight";
import * as sleepService from "../services/sleep";
import * as moneyService from "../services/money";
import * as journalService from "../services/journal";
import * as titanModeService from "../services/titan-mode";
import * as progressionService from "../services/progression";
import * as achievementsService from "../services/achievements";

// ─── Helpers ────────────────────────────────────────────────────────────────

function bootstrapDoneKey(userId: string, domain: string): string {
  return `bootstrap_${domain}_done:${userId}`;
}

function isBootstrapDone(userId: string, domain: string): boolean {
  return storage.getBoolean(bootstrapDoneKey(userId, domain)) === true;
}

function markBootstrapDone(userId: string, domain: string): void {
  storage.set(bootstrapDoneKey(userId, domain), true);
}

/** Run a single bootstrap step with skip-if-done + error-isolation. */
async function runBootstrap(
  userId: string,
  domain: string,
  fn: () => Promise<void>,
): Promise<void> {
  if (isBootstrapDone(userId, domain)) return;
  try {
    await fn();
    markBootstrapDone(userId, domain);
  } catch (e) {
    logError(`bootstrap.${domain}`, e);
    // Don't mark done on failure — next sign-in will retry.
  }
}

// ─── Per-domain bootstrappers ───────────────────────────────────────────────

async function bootstrapBudgets(): Promise<void> {
  // Skip if local already has data — the migration is the source of truth.
  const local = getJSON<Array<{ id: number }>>("budgets", []);
  if (local.length > 0) return;

  const cloud = await budgetsService.listBudgets();
  if (cloud.length === 0) return;

  // Map cloud rows back to legacy MMKV shape (id: number).
  // Legacy used numeric ids generated by nextId(); since we don't have
  // those anymore on a fresh device, we just use sequential indices.
  const local_rows = cloud.map((row, i) => ({
    id: i + 1,
    category: row.category,
    monthlyLimit: row.monthly_limit,
  }));
  setJSON("budgets", local_rows);
}

async function bootstrapWeight(): Promise<void> {
  const local = getJSON<Array<unknown>>("weight_entries", []);
  if (local.length > 0) return;

  const cloud = await weightService.listWeightLogs();
  if (cloud.length === 0) return;

  const rows = cloud.map((r) => ({
    dateKey: r.date_key,
    weightKg: Number(r.weight_kg),
    createdAt: new Date(r.created_at).getTime(),
  }));
  setJSON("weight_entries", rows);
}

async function bootstrapSleep(): Promise<void> {
  const allKeys = storage.getAllKeys() as string[];
  const hasLocal = allKeys.some((k) => k.startsWith("sleep:"));
  if (hasLocal) return;

  const cloud = await sleepService.listSleepLogs();
  if (cloud.length === 0) return;

  for (const row of cloud) {
    const minutes = row.hours_slept ? Number(row.hours_slept) * 60 : 0;
    setJSON(`sleep:${row.date_key}`, {
      dateKey: row.date_key,
      bedtime: "00:00",
      wakeTime: "00:00",
      durationMinutes: minutes,
      quality: row.quality ?? 3,
      notes: row.notes ?? "",
    });
  }
}

async function bootstrapMoney(): Promise<void> {
  const local = getJSON<Array<unknown>>("money_txs", []);
  if (local.length > 0) return;

  const cloud = await moneyService.listTransactions({});
  if (cloud.length === 0) return;

  const rows = cloud.map((tx, i) => ({
    id: i + 1,
    dateISO: tx.date_key,
    type: tx.type as "expense" | "income",
    amount: Number(tx.amount),
    category: tx.category,
    note: tx.note ?? "",
  }));
  setJSON("money_txs", rows);
}

async function bootstrapJournal(): Promise<void> {
  const allKeys = storage.getAllKeys() as string[];
  const hasLocal = allKeys.some((k) => k.startsWith("journal:"));
  if (hasLocal) return;

  const cloud = await journalService.listJournalEntries();
  if (cloud.length === 0) return;

  for (const row of cloud) {
    setJSON(`journal:${row.date_key}`, {
      date_key: row.date_key,
      content: row.content,
      updated_at: new Date(row.updated_at).getTime(),
    });
  }
}

async function bootstrapTitanMode(): Promise<void> {
  const local = getJSON<unknown>("titan_mode", null);
  if (local) return;

  const cloud = await titanModeService.getTitanModeState();
  if (!cloud) return;

  setJSON("titan_mode", {
    unlocked: cloud.unlocked,
    consecutiveDays: cloud.consecutive_days,
    averageScore: Number(cloud.average_score),
    startDate: cloud.start_date,
    lastRecordedDate: cloud.last_recorded_date,
  });
}

async function bootstrapProgression(): Promise<void> {
  const local = getJSON<unknown>("progression_phase", null);
  if (local) return;

  const cloud = await progressionService.getProgression();
  if (!cloud) return;

  setJSON("progression_phase", {
    currentPhase: cloud.current_phase,
    currentWeek: cloud.current_week,
    phaseStartWeek: cloud.phase_start_week,
    firstUseDate: cloud.first_use_date,
    phaseStartDate: cloud.phase_start_date,
    history: cloud.phase_history ?? [],
  });
}

async function bootstrapAchievements(): Promise<void> {
  const local = getJSON<{ unlockedIds?: string[] } | null>("achievements_unlocked", null);
  if (local && Array.isArray(local.unlockedIds) && local.unlockedIds.length > 0) return;

  const cloud = await achievementsService.listUnlockedAchievements();
  if (cloud.length === 0) return;

  const unlockedIds = cloud.map((u) => u.achievement_id);
  setJSON("achievements_unlocked", {
    unlockedIds,
    unlockedMap: Object.fromEntries(
      cloud.map((u) => [u.achievement_id, { unlockedAt: u.unlocked_at }]),
    ),
  });
}

// ─── Public API ─────────────────────────────────────────────────────────────

/**
 * Run all bootstrap steps for the current user. Idempotent — already
 * done domains are skipped via per-user MMKV flags. Errors don't
 * propagate (each domain is wrapped in try/catch and logged).
 */
export async function bootstrapFromCloud(userId: string): Promise<void> {
  await runBootstrap(userId, "budgets", bootstrapBudgets);
  await runBootstrap(userId, "weight", bootstrapWeight);
  await runBootstrap(userId, "sleep", bootstrapSleep);
  await runBootstrap(userId, "money", bootstrapMoney);
  await runBootstrap(userId, "journal", bootstrapJournal);
  await runBootstrap(userId, "titan_mode", bootstrapTitanMode);
  await runBootstrap(userId, "progression", bootstrapProgression);
  await runBootstrap(userId, "achievements", bootstrapAchievements);
}
